version: '3.1'

services:
  postgresql:
    container_name: contact_book
    restart: always
    image: postgres:10.10-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres+mb+2019
      POSTGRES_DB: contact_book
    ports:
      - 0.0.0.0:5432:5432
